name: Parse and Comment back on issue
on:
  issues:
    types: ['opened']
  issue_comment:
    types: ['created']

jobs:
  parse-issue:
    if: github.event_name != 'push' && github.event_name != 'pull_request' || contains(github.event.comment.body, '/validate')
    runs-on: ubuntu-latest
    name: Parse issue, scan and comment back for non-inclusive language
    steps:
      - name: NIL Reporter
        uses: gkarthiks/nil-issue-reporter@0.2.0
        id: parseissue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: non-inclusive
